DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS COMMENT;

CREATE TABLE DOCUMENT(ID UUID PRIMARY KEY, NAME VARCHAR(255), TITLE VARCHAR(255), INDEX_NAME VARCHAR(255), INDEX_VALUE VARCHAR(255), CONTENT VARCHAR(255));
CREATE TABLE COMMENT(ID UUID, USER_ID UUID, CONTENT VARCHAR(255), FOREIGN KEY (USER_ID) REFERENCES DOCUMENT(ID));